### ISSUE TITLE
Dosya yapısı geliştirmeleri

### ISSUE THREAD

**Issue by mertssmnoglu** [nlabscli/cli#2]
Bir cli uygulamasının en önemli özelliklerinden biri olan yardım menüsü zaten programmer modülü ile tamamlanmış durumda.
Kalan kısımlarda da komutları `src/command` içerisinden dinamik olarak veya statik olarak çekmek mantıklı olabilir.

**Comment by turkmvc** [comment]
bu ilk test idi bir deneme idi elbette geliştirebilirim ama hiç bir framework tek başına süper uber birşey çıkarmak o kadar basit olamaz olsa idi herkes bir framework yazar digerlerini kullanmazdı sanırım :)
ama bakacagım birkaç ekleme yapabilirim müsait zamanımda

**Comment by turkmvc** [comment]
dikkate aldım söylediklerinizi

**Comment by turkmvc** [comment]
ve gerekli eklemeleri müsait oldugum vakit yapacagım
